name: EpicRPGSkillsAndQuests
version: 2.0.3
main: me.Vark123.EpicRPGSkillsAndQuests.Main
author: Vark123
depend: [EpicCalendarEvents,MythicMobs,Multiverse-Core,EpicParty,NBTAPI,EpicRPG,EpicNPC,EpicInventory]
softdepend: [EpicRPGFishing]
api-version: 1.21

commands:
  quests:
    aliases: [quest, zadania, zadanie, misje, misja, questy, q]
  zlecenie:
    aliases: [zlecenia]
  dungeon:
    aliases: [dungeons, loch, lochy]
  raid:
    aliases: [rajd, rajdy, raids]
  raidadmin:
    aliases: [raida, radmin]
  questgm: